[build]
  command = "npm run build"
  publish = "site/"
[[redirects]]
  from = "/tutorials/getting-started/"
  to = "/tutorials/creating/getting-started/"
[[redirects]]
  from = "/tutorials/git/"
  to = "/tutorials/creating/git/"